
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from  './components/shared/Navbar.jsx';
// import { Toaster } from "react-hot-toast";

// import ProgressBar from "./components/progressbar";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Job portal",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
   
    
  
    
     
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//            <Providers>
//           <ProgressBar/>
//   <Navbar/>
//         {children}
//         </Providers>
//       </body>

    
      
//     </html>
//   );
// }
// app/layout.js
import { Providers } from "./provider.js";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar.jsx";
import { Toaster } from "react-hot-toast";
import ProvidersWrapper from "@/app/providers/ProvidersWrapper"; // 👈 updated import
import ProgressBar from "./components/progressbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Job portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ProvidersWrapper>
          
          <ProgressBar />
          <Navbar />
          <Toaster position="top-center" />
          {children}
        </ProvidersWrapper>
      </body>
    </html>
  );
}
